### ISSUE TITLE
Request for synced Leaflet maps code

### ISSUE THREAD

**Issue by ascheeres** [Drexel-UHC/shinyUHC#3]
I am working on a vital statistics R Shiny dashboard for the Philadelphia Dept of Public Health, which includes several Leaflet maps. I am requesting code to sync Leaflet maps that are embedded in an R Shiny dashboard.

**Comment by ran-codes** [comment]
@ascheeres You can get example code of a demo shiny app with a **sync map** via the [shinyUHC::initializeShinyApp()](https://drexel-uhc.github.io/shinyUHC/reference/initializeShinyApp.html) function. 

How to install the package: https://drexel-uhc.github.io/shinyUHC/index.html
Function documentation: https://drexel-uhc.github.io/shinyUHC/reference/initializeShinyApp.html

You can find the sync map in its own tab and the codebase in its own module in ./app/R/modules/SyncMap.R.
 Let me know how the function works for you or any suggestions in terms of documentation. We are still in the ideation/prototyping phase of this package; so bugs are expected. Thanks for helping us test it! 😄
