### ISSUE TITLE
Request for customized R Shiny dashboard loading page code

### ISSUE THREAD

**Issue by ascheeres** [Drexel-UHC/shinyUHC#4]
I am working on a vital statistics R Shiny dashboard for the Philadelphia Dept of Public Health and would like to replace the generic "Please Wait" loading page with a customized loading page that includes our logo. I am requesting code to create this customized loading page.

**Comment by rl627** [comment]
@ascheeres You can get example code of a demo shiny app with a loading page via the [shinyUHC::initializeShinyApp()](https://drexel-uhc.github.io/shinyUHC/reference/initializeShinyApp.html) function.

- How to install the package: https://drexel-uhc.github.io/shinyUHC/index.html
- Function documentation: https://drexel-uhc.github.io/shinyUHC/reference/initializeShinyApp.html

Let me know how the function works for you or any suggestions in terms of documentation. We are still in the ideation/prototyping phase of this package; so bugs are expected. Thanks for helping us test it! 😄
